### ISSUE TITLE
golang.org/x/net/icmp

### ISSUE THREAD

**Issue by porjo** [tatsushid/go-fastping#7]
Thanks for the package. 

Not sure which came first, but is there any reason why you wouldn't use [golang.org/x/net/icmp](https://godoc.org/golang.org/x/net/icmp) instead of your own icmp.go?

**Comment by tatsushid** [comment]
I can't remember for sure but when I wrote this, there wasn't enough functionality in the package but now it has so I changed to use it instead of my own. Thanks for your comment!

**Comment by glyn** [comment]
Can this issue now be closed?
